version: "3.2"
services:
    nginx:
        image: nginx:1.19.3-alpine
        restart: on-failure
        ports:
            - 80:80
        depends_on:
            - mysql
        networks:
            - rede-interna
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dbnginx
            MYSQL_USER: adminnginx
            MYSQL_PASSWORD: Password1234!
        networks:
            - rede-interna
networks:
  rede-interna:
    driver: bridge
    name: rede-interna